/**
 * Root Layout Component
 * 
 * The root layout for the Next.js application.
 * Defines the HTML structure and metadata for all pages.
 * Applies global styles and sets up the document structure.
 */

import './globals.css';
import type { Metadata } from 'next';

/**
 * Metadata configuration for the application
 * Used for SEO and browser tab information
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root Layout Component
 * 
 * @param children - React nodes to be rendered as page content
 * @returns JSX structure with HTML and body elements
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}